### ISSUE TITLE
yarn install unable to access https://github.com/frozeman/bignumber.js-nolookahead.git

### ISSUE THREAD

**Issue by Jeremyyang** [MetaMask/template-snap#28]
When `git clone` the repo and execute `yarn install`, it throws:
```
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/frozeman/bignumber.js-nolookahead.git
Directory: /Users/projects/ethereum/hello-snap
Output:
fatal: unable to access 'https://github.com/frozeman/bignumber.js-nolookahead.git/': Failed to connect to github.com port 443: Connection refused
```

then `git config --global url.https://github.com/.insteadOf git://github.com/` via [stackoverflow](https://stackoverflow.com/questions/1722807/how-to-convert-git-urls-to-http-urls), it throws:

```
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/frozeman/bignumber.js-nolookahead.git
Directory: /Users/projects/ethereum/hello-snap
Output:
fatal: unable to connect to github.com:
github.com[0: ::1]: errno=Connection refused
github.com[1: 127.0.0.1]: errno=Connection refused
```
And I've removed all proxy with `git config --global --unset http.proxy`, then Connection refused is still unsolved.

Could someone help me?

**Comment by FrederikBolding** [comment]
Thanks for reporting this! I am unable to produce this locally.

I'm wondering if this is a configuration issue somewhere on your local machine since you can access GitHub to post this issue but can't install a dependency located on GitHub 🤔

**Comment by Jeremyyang** [comment]
Yes, it's caused by the operator network , I set an environment variable in my local machine, then it works!
```
export https_proxy=http://127.0.0.1:port
```
Thank you all the same
