### ISSUE TITLE
Setup template-snap front-end

### ISSUE THREAD

**Issue by GuillaumeRx** [MetaMask/template-snap#30]
Setup all the front-end for the template-snap repo.

TODO :

- [x] Setup React

- [x] Implement new designs

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-Platform-615b3a7c08d2b20015eb6c4e/issues/MetaMask/template-snap/30?planning-poker) with ZenHub @david0xd @FrederikBolding @GuillaumeRx @hmalik88 @Mrtenz @ritave

**Comment by eriknson** [comment]
[Redesign](https://www.figma.com/file/dutBhkCkR1eeuxIRcHNNiS/Template-Snap?node-id=1%3A12). Pop me a dm when we're kicking this off.

**Comment by GuillaumeRx** [comment]
This issue is opened in the wrong repo, linking PR to the parent issue.
