### ISSUE TITLE
Template snap hosted at metamask.github.io/template-snap still using `registerRpcMessageHandler`

### ISSUE THREAD

**Issue by ziad-saab** [MetaMask/template-snap#41]
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/3943143/185525079-57b3f3a7-7396-48a1-90c7-5cdf48ee4872.png">

This prevents installation of the snap

To Do:
- [ ] Update `package.json` and `snap.manifest.json` version numbers
- [ ] Publish the latest version of `template-snap` on NPM

**Comment by Montoya** [comment]
This is being resolved by deprecating template-snap

Going forward, template-snap-monorepo is the official template to be used
